# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: 'Coffee'
day_night: true
font: 'Mr Robot'
font_size: L
noTimes: true

# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

email: test@example.org
appointment_url: 'https://calendly.com'
contact_links:
  - icon: comments
    icon_pack: fas
    name: Discuss on the forum
    link: 'https://github.com/wowchemy/wowchemy-hugo-modules/discussions'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: ""
time_format: ""
address_format: en-us

# Site features

highlight: false
highlight_languages: []
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: false
docs_section_pager: false
sharing: true

copyright_license:
  enable: true
  notice: >-
    Lisensi di bawah {license}, website dikembangkan oleh Dwipayana.

abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider:
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  local_backend: false
icon:
  pack:
    ai: false
